### PR TITLE
Issue #7.  Moved More Information to be the first tab.

### PR DESCRIPTION
**Pull request by courtneylknoth**
Submitting updates for Issue #7.  Moved "More Information" to be the first tab.

### CODE REVIEW

**Comment by ajkeith** [comment]
@courtneylknoth sorry for the delay on this - I've had my local version in a in-between state. I'm hoping to get to merge this tonight. Can you send a screenshot of how the new tab looks for discussion?

**Comment by courtneylknoth** [comment]
image
 
This is what it currently looks like.  I really prefer the information tab where it use to be (maybe we could make it a different color).  I also think I should better utilize all of the space on this tab.  What are your thoughts?

**Comment by ajkeith** [comment]
Is there a way that we could include some introductory title and/or text before the links to the more detailed info?

**Comment by ajkeith** [comment]
Closing for now while the issue gets worked a bit more.

**Pull request closed without merging**
